version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_ADMIN=$DB_ADMIN
      - DB_ADMIN_PWD=$DB_ADMIN_PWD
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
